### ISSUE TITLE
Bug: fix favicon url

### ISSUE THREAD

**Issue by geromegrignon** [bonjour-angular/apprendre#18]
# Description

Le favicon n'apparait pas actuellement dans le navigateur.
Starlight s'attend par design à ce que l'icone soit dans le répertoire `public`, qui est donc redondant dans la configuration du repository.

Il faut remplacer `/public/favicon.png` par `favicon.png`.

**Comment by KevTale** [comment]
Fixed! Merci @geromegrignon
